version: '3.8'

networks:
  192-168-10-64-net:
    external: true

services:
  dashmachine:
    image: "rmountjoy/dashmachine:develop"
    restart: "always"
    networks:
      - 192-168-10-64-net
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/dashmachine:/dashmachine/dashmachine/user_data
#    cap_add:
#      - NET_ADMIN
